SSH_USER=ubuntu
APP_HOME=/var/www/admin.taxplancanada.ca
SERVER=staging.taxplancanada.ca

SET_PATH="export PATH=/home/ubuntu/.rbenv/plugins/ruby-build/bin:/home/ubuntu/.rbenv/shims:/home/ubuntu/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
SET_RBENV="rbenv global 2.3.1 && rbenv rehash"
GO_HOME="cd $APP_HOME"
GIT_FETCH="git fetch"
GIT_CHECKOUT="git checkout $Tag"
GIT_PULL="git pull"
NPM_INSTALL="npm install"
NODE_STOP="sudo -E npm stop"
NODE_START="sudo -E npm start"

ssh -o StrictHostKeyChecking=no  $SSH_USER@$SERVER << EOF
$SET_PATH
$SET_RBENV
$GO_HOME
$GIT_FETCH
$GIT_CHECKOUT
$GIT_PULL
$NODE_STOP
$NPM_INSTALL
$NODE_START
EOF
